// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: get_user_from_id.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const getUserFromID = `-- name: GetUserFromID :one
SELECT id, email, is_chirpy_red
FROM users
WHERE id = $1
`

type GetUserFromIDRow struct {
	ID          uuid.UUID
	Email       string
	IsChirpyRed sql.NullBool
}

func (q *Queries) GetUserFromID(ctx context.Context, id uuid.UUID) (GetUserFromIDRow, error) {
	row := q.db.QueryRowContext(ctx, getUserFromID, id)
	var i GetUserFromIDRow
	err := row.Scan(&i.ID, &i.Email, &i.IsChirpyRed)
	return i, err
}
