// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: update_user_email_password.sql

package database

import (
	"context"
	"time"
)

const updateUserPasswordEmail = `-- name: UpdateUserPasswordEmail :one
UPDATE users
SET hashed_password = $1, email = $2, updated_at = $3
RETURNING id, created_at, updated_at, email, hashed_password
`

type UpdateUserPasswordEmailParams struct {
	HashedPassword string
	Email          string
	UpdatedAt      time.Time
}

func (q *Queries) UpdateUserPasswordEmail(ctx context.Context, arg UpdateUserPasswordEmailParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserPasswordEmail, arg.HashedPassword, arg.Email, arg.UpdatedAt)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.HashedPassword,
	)
	return i, err
}
